/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <serialise.h>
#include <stdint.h>
#include "serial.h"
#include "game.h"
#include "timer.h"
#include "digital_io.h"
#include "ADC.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int8_t presses = 0;  // Initialize to 0
int8_t button_IR1 =0;
int8_t button_IR2 =0;
int8_t button_IR3 =0;

void callback1(uint32_t length) {
    // Copy the packet data to a local buffer for processing
    uint8_t local_buffer[256];

    // Ensure we don't exceed buffer bounds
    uint16_t copy_length = (length < 256) ? length : 256;

    // Copy packet data from the serial port buffer
    for (uint16_t i = 0; i < copy_length; i++) {
        local_buffer[i] = USART1_PORT.packet_buffer[i];
    }

    // Process the copied packet
    process_received_packet(local_buffer, copy_length);
}

void buttoncallback(void){
    presses++;

    switch (presses){
        case 1:
        	button_IR1 = 1;
            break;
        case 2:
        	button_IR2 = 1;
            break;
        case 3:
        	button_IR3 = 1;
            break;
        default:
            // Reset after 3 presses
            presses = 0;
            break;
    }


    // Monitor the new IR state
    IR_monitoring(button_IR1, button_IR2, button_IR3);
}

int8_t check_IR_changes(void) {
    return ADC_CheckIRChanges();
}

int main(void)
{
	System_Init();
    // Initialize all systems once
    SerialInitialise(BAUD_115200, &USART1_PORT, &callback1);
    enable_interrupt_USART1_PC11();
    //ADC_Initialize();
    DigitalInitialise(&buttoncallback);  // Initialize once, outside the loop


    while (1) {

        // Check if any IR sensor values have changed
        if (check_IR_changes()) {
        	delay(1000);
            //Get current IR values and pass to IR_monitoring
           IR_values current_ir = ADC_GetCurrentIRValues();
           IR_monitoring(current_ir.IR1, current_ir.IR2, current_ir.IR3);
        }


    }
}
