/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "serial.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	for (volatile int i = 0; i < 800000; i++); // 100ms-ish delay


	SerialInitialise(BAUD_115200, &USART1_PORT, 0x00);
	SerialInitialise(BAUD_115200, &USART2_PORT, 0x00);

	enable_interrupt_USART1_PC11();
	enable_interrupt_USART2_PA3();

//	while (1) {
//		uint8_t data;
//		if (SerialReceiveChar(&USART1_PORT, &data)) {
//			SerialOutputChar(data, &USART1_PORT);
//		}
//	}
    /* Loop forever */
	for(;;);
}
